# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: pwd & ls -lah
      - name: Install Hugo CLI
        run: |
          sudo apt install -y hugo
      - name: Checkout Resources Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: suryastef/website-resources
      - name: Move Resources to workdir
        run: pwd && ls -lah && mv links/* .
      - name: Checkout Hugo Theme
        uses: actions/checkout@v3
        with:
          repository: jpanther/lynx
          path: themes/lynx
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Debug
        run: pwd & ls -lah
      - name: Update Footer
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'themes/lynx/i18n/en.yaml'
          propertyPath: 'footer.powered_by'
          value: ""
          commitChange: false
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          retention-days: 1
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v1
        name: Deploy to GitHub Pages
        id: deployment
